### PR TITLE
feat: commitlint

### LINKED ISSUE #30: git commit msg
添加

feat: msg
fix: msg

这种形式的msg内容兼容

### PR DESCRIPTION
**Pull request by XyyF**

### CODE REVIEW

**Comment by XyyF** [comment]
issue: #30

**Comment by mistricky** [comment]
分支名有问题，这个流程:

fork -> checkout a new branch -> dev -> create PR -> review -> merge into master

**Comment by mistricky** [comment]
commit message 规范 [Operator] message

**Comment by XyyF** [comment]
#30

**Pull request closed without merging**
